# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32cbc7412c44839625184e7444d2cddc09d718b0e4575cc848bbb3378aa8df1e74c82e3ea3f8f1dd4f93c0af745d985f8f458e559e055762cedf3dfdddb23b69

test:
  secret_key_base: 8c069670021b71638401557bb619f4f145366f2b9ad171aa8c09760001c1c138ffb405ee2846bf8dac443636910bb522fb4b5072f9688e29ef88f4a4bf7cdfda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
